name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependências
      run: |
        cd engenharia-software
        npm ci

    - name: Executar testes
      run: |
        cd engenharia-software
        npm run test:ci

    - name: Executar build
      run: |
        cd engenharia-software
        npm run build

    - name: Upload de artefatos de build
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-node-${{ matrix.node-version }}
        path: |
          engenharia-software/build/
          engenharia-software/package*.json
        retention-days: 30

    - name: Upload de relatórios de teste
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-node-${{ matrix.node-version }}
        path: engenharia-software/coverage/
        retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Download de artefatos
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts-node-20.x
        path: ./artifacts
        
    - name: Deploy (simulação)
      run: |
        echo "🚀 Realizando deploy do sistema de gerenciamento de usuários..."
        echo "📦 Artefatos disponíveis:"
        ls -la ./artifacts/
        echo "✅ Deploy realizado com sucesso!"