name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-results/test-results.xml

  build:
    runs-on: ubuntu-latest
    needs: tests # Garante que o build só rode após os testes passarem
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-package
          path: build/ # Assumindo que o script de build gera os arquivos na pasta 'build'

notify:
  runs-on: ubuntu-latest
  needs: [tests, build] # Precisa da construção de 'build' do outro membro se não nao roda
  if: always() # caso falhe testes e buids roda de qualquer jeito (._.)
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Send email notification
      run: node scripts/send_email.js
      env:
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        PIPELINE_STATUS: ${{ job.status }}

